version: '3.8'

services:
  # 前端服务
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - quant-trading-network

  # 后端服务（假设后端也在 Docker 中）
  backend:
    image: quant-trading-backend:latest
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/quant_trading
      - SECRET_KEY=your-secret-key
    depends_on:
      - db
    networks:
      - quant-trading-network

  # 数据库服务
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=quant_trading
      - MYSQL_USER=quant_user
      - MYSQL_PASSWORD=quant_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - quant-trading-network

  # Redis 缓存（可选）
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - quant-trading-network

volumes:
  mysql_data:
  redis_data:

networks:
  quant-trading-network:
    driver: bridge
